Repository srimani-programmer/Breast-Cancer-Predictor, pull requests merged in 2021-04, with the labels that each got.

#94 Added a CNN Model with 97.96% accuracy And Data Visualization file for issue #96
  Model/CNN.py
  Visualization/Data Visualization_1.py
  requirements.txt
Labels: GSSOC21, approved, level2, merged

#116 Added visualizations for numerical data using Plotly
  .github/config.yml
  README.md
  Visualization/plotly_visualizations.py
  requirements.txt
Labels: GSSOC21, approved, level2

#97 Auto scroll added
  __pycache__/implementation.cpython-39.pyc
  __pycache__/random_forest.cpython-39.pyc
  static/css/style.css
  static/js/main.js
  templates/home.html
Labels: GSSOC21, approved, level1

#107 [Gssoc'21] Added the back to top button and favicon
  __pycache__/implementation.cpython-37.pyc
  __pycache__/random_forest.cpython-37.pyc
  templates/home.html
Labels: GSSOC21, approved, level0, merged

#108 Closes #106 Added plots files
  Visualization/PLOTS/boxplot - area_mean.png
  Visualization/PLOTS/boxplot - compactness_mean.png
  Visualization/PLOTS/boxplot - concave points_mean.png
  Visualization/PLOTS/boxplot - concavity_mean.png
  Visualization/PLOTS/boxplot - fractal_dimension_mean.png
  Visualization/PLOTS/boxplot - perimeter_mean.png
  Visualization/PLOTS/boxplot - radius_mean.png
  Visualization/PLOTS/boxplot - smoothness_mean.png
  Visualization/PLOTS/boxplot - symmetry_mean.png
  Visualization/PLOTS/boxplot - texture_mean.png
  Visualization/PLOTS/density vs area_mean.png
  Visualization/PLOTS/density vs compactness_mean.png
  Visualization/PLOTS/density vs concave points_mean.png
  Visualization/PLOTS/density vs concavity_mean.png
  Visualization/PLOTS/density vs fractal_dimension_mean.png
  Visualization/PLOTS/density vs perimeter_mean.png
  Visualization/PLOTS/density vs radius_mean.png
  Visualization/PLOTS/density vs smoothness_mean.png
  Visualization/PLOTS/density vs symmetry_mean.png
  Visualization/PLOTS/density vs texture_mean.png
  Visualization/PLOTS/heatmap.png
  Visualization/PLOTS/scatter matrix.png
Labels: GSSOC21, approved, level1, merged
