Repository srimani-programmer/Breast-Cancer-Predictor, pull requests merged in 2022-04, with the labels that each got.

#200 VGG16 Training Notebook with 0.947 Validation Accuracy
  ModelS DRIVE.txt
  ensemble_modelling_test_accuracy_of_96_05.py
  transfer_learning_using_vgg16_0.97368_val_accuracy.py
Labels: changes-requested, GSSoc22

#184 #176 Keras CNN Model added
  Model/bc_prediction_cnn.py
  cnn_app.py
  cnn_model.h5
Labels: Level2, GSSoc22, ready-to-merge

#168 Fixed #155 & #164
  app.py
  implementation.py
  templates/result.html
Labels: GSSoc22, ready-to-merge
